version: 2.0.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform: Any CPU
build_script:
- cmd: build.cmd
test: off
notifications:
- provider: Slack 
  incoming_webhook:
      secure: 8HsB7ugtiao2POPBIleKwZhgUm/eXfndfmhRN9ewMr/JnWQARH4EK698Hzb/zzuuO81RKFJQmaYWfZSEWdCugEFXpED+5yo/3ICOzaiXHBI=
  method: POST
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: 'Artifacts\Packages\*.nupkg'
    name: NFluentPackages