version: 2.0.{build}.0
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform: Any CPU
build_script:
- cmd: build.cmd
test: off
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
artifacts:
  - path: 'Artifacts\Packages\*.nupkg'
    name: NFluentPackages