version: 2.0.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU

image: Visual Studio 2017

before_build:
- cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%

build_script:
- cmd: build.cmd
test: off
artifacts:
  - path: 'Artifacts\Packages\*.nupkg'
    name: NFluentPackages