version: 2.0.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform: Any CPU
build_script:
- cmd: CI.cmd
test: off

artifacts:
  - path: 'Artifacts\Packages\*.nupkg'
    name: NFluentPackages

environment:
  NFLUENT_NUGET_API_KEY: aeZH+rScDM4gdvzDlCPeBHGEX2G+eACBSI8yrsmXLJpyDgXpRj07Xk1sw+KuH2xM

assembly_info:
  patch: true
  file: version.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
- provider: GitHubPullRequest
  template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
  auth_token:
      secure: kCICf0+4Cc7GIVkQ072LtcxBKKhynEsSx612WwmUi3NAs8C/14iHy7PlXTUWyyYR9
      