version: 2.0.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU

image: Visual Studio 2017

build_script:
- cmd: build.cmd
test: off
artifacts:
  - path: 'Artifacts\Packages\*.nupkg'
    name: NFluentPackages